### ISSUE TITLE
Does not compile on 4.9.0

### ISSUE THREAD

**Issue by ree85** [dbason/crystalhd#22]
Since the latest commit (7fb5ccc1be7e5fc3bf15b216ec225681c00f29b8) the code does not build on 4.9.0.

My system complains about a missing "linux/sched/signal.h".

If I change
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,9,0)
to
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,10,0)
it builds.

File:
driver/linux/crystalhd_cmds.c
```
1 | 2
-- | --
  | @@ -24,6 +24,11 @@
  |   | * along with this driver.  If not, see <http://www.gnu.org/licenses/>.
  |   | **********************************************************************/
  |   |  
  |   | +#include <linux/version.h>
  |   | +#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,9,0)
  |   | +#include <linux/sched/signal.h>
  |   | +#endif
  |   | +
  |   | #include "crystalhd_lnx.h"
  |   | #include "crystalhd_hw.h"
  |   |  
```

**Comment by NTICompass** [comment]
Looks like a typo here: https://github.com/dbason/crystalhd/commit/6b1bf038b19413a80d3991e916f81ba2bdf4d760

The rest are 4,11,0 except the first one...
