### ISSUE TITLE
Kernel signature 

### ISSUE THREAD

**Issue by ewingate** [dbason/crystalhd#6]
I've been working on getting this card working on my system and your repository is getting me further ahead than any other.  I'm getting a failure on the dmesg step.

```
$ dmesg | grep crystalhd
[    5.364608] crystalhd: module verification failed: signature and/or required key missing - tainting kernel
[    5.396671] Loading crystalhd v3.10.0
[    5.396722] crystalhd 0000:04:00.0: Starting Device:0x1615
```

Do you have any insights for me?

**Comment by dlenski** [comment]
The "tainting kernel" line does _not_ indicate any kind of functional failure. As you can see from the following lines, the module loaded successfully. Are you able to use the `crystalhd` device?

Kernel tainting basically just means "you have loaded an unsupported driver, so don't bug the official kernel developers if your system malfunctions." You may want to read more about what it means. Here's a good explanation: http://unix.stackexchange.com/a/118117/58453

**Comment by ewingate** [comment]
I suspected it was alright.  I've got the indicator app loaded up and it switches on but in VLC with the crystalhd codec enabled HD video isn't playing correctly.  I'm getting a black screen with audio with 1080P 60fps GoPro videos.  Kodi plays them - but very slowly and with glitches.

**Comment by dlenski** [comment]
Hmm...what kernel and distro are you running? (`uname -a` and `lsb_release -a` should give me all the details)

If I recall correctly, VLC prints some extra info about the crystalhd device initialization when it starts up.

Do you see anything there, or in subsequent `dmesg` output, that might be useful?

**Comment by ewingate** [comment]
Here are the outputs from uname and lsb_release:

uname -a
Linux ROJA 4.4.0-36-generic #55~14.04.1-Ubuntu SMP Fri Aug 12 11:49:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
edward@ROJA:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:   trusty

**Comment by dlenski** [comment]
I'm a bit stumped. Let me see if I've got this straight:
1. Without using the crystalhd driver, VLC will play your videos correctly, but slowly?
2. But _with_ the crystalhd driver, you just get a black window?
3. There's nothing interesting in VLC's stdout, nor anything in `dmesg` while the video is playing…?

If that's all correct, then exactly what video hardware and X11 display driver do you have? (`glxinfo |grep -C10 Device` should give the relevant details)

**Comment by ewingate** [comment]
No.  Without the crystalhd driver VLC won't play the videos at all, I just get some still images that change every so often.  With the crystalhd driver I get a black screen and audio.  With the crystalhd driver and Kodi I get slow glitchy video.

I've got a Mobility Radeon HD 3200 (RS780M) and a Radeon driver (glxinfo vendor string is Mesa Project and SGI).

Sorry for this.

**Comment by dlenski** [comment]
> No. Without the crystalhd driver VLC won't play the videos at all, I just get some still images that change every so often. 

If the video isn't playable with a _software decoder_… how can you be sure it's actually correctly encoded? This may not have anything to do with crystalhd at all.

I suggest trying some MPEG2 test videos (try http://www.w6rz.net for some examples, like the Big Buck Bunny open-source movie).

If you can play well-known MPEG2/H.264 test videos with crystalhd, then I'd say the problem is with the format of your videos, not with the driver.

> I've got a Mobility Radeon HD 3200 (RS780M) and a Radeon driver (glxinfo vendor string is Mesa Project and SGI).

Now I'm really confused. The Radeon HD 3200 should have built-in [video acceleration hardware](https://en.wikipedia.org/wiki/Unified_Video_Decoder). Why would you need to use `crystalhd`?

I think almost everyone using `crystalhd` is using it as an add-on for older Intel Atom chipsets that have (a) slow CPUs and (b) no built-in video decoding hardware.

**Comment by ewingate** [comment]
Yea, I'm questioning my sanity as well.  The video output on this has always been an issue and someone suggested throwing a video accelerator in the spare mini PCI slot.
